pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net" }

        gradlePluginPortal()
    }
}

rootProject.name = 'emi_letsdo_compat'

include("common")
include("fabric")
include("neoforge")