package com.pandaismyname1.emiletsdocompat;

import net.minecraft.resources.ResourceLocation;

public class MockRecipeIdGenerator {
    private static long counter = 0;

    public static ResourceLocation generateRecipeId() {
        return ResourceLocation.fromNamespaceAndPath(Emi_letsdo_compat.MOD_ID, "autogenerated_" + counter++);
    }
}
