modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/Pandaismyname1/Let-s-Do-EMI-Compat"
[[mods]]
modId = "emi_letsdo_compat"
version = "${version}"
displayName = "emi-letsdo-compat"
logoFile = "icon.png" #optional
description = '''

'''
[[dependencies.emi_letsdo_compat]] #optional
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "AFTER"
side = "CLIENT"
# Here's another dependency
[[dependencies.emi_letsdo_compat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.emi_letsdo_compat]]
modId = "architectury"
mandatory = true
versionRange = "[0.107.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.emi_letsdo_compat]]
modId = "emi"
mandatory = true
versionRange = "[1.1.13,)"
ordering = "AFTER"
side = "CLIENT"
