plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}
architectury {
    platformSetupLoomIde()
    neoForge()
}
loom {
    accessWidenerPath.set(project(":common").loom.accessWidenerPath)
    runs {
        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    repositories {
        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/"
        }
        repositories {
            maven {
                url "https://cursemaven.com"
            }
        }
    }

    neoForge "net.neoforged:neoforge:${neo_forge_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"

//    modImplementation "curse.maven:lets-do-vinery-704465:5992486"
//    modImplementation "curse.maven:lets-do-bakery-886559:5528402"
    modImplementation "curse.maven:lets-do-meadow-821483:7069148"
//    modImplementation "curse.maven:lets-do-candlelight-846962:5427646"
//    modImplementation "curse.maven:lets-do-brewery-971636:5427504"
    modImplementation "curse.maven:lets-do-herbal-brews-951221:7001991"
    modImplementation "curse.maven:lets-do-beachparty-858691:7021359"
    modImplementation "curse.maven:lets-do-farm-charm-1038103:7081972"
    modImplementation "curse.maven:lets-do-bakery-farm-charm-compat-1038130:7032843"
    modImplementation "curse.maven:lets-do-candlelight-farm-charm-compat-1038117:7066667"
    modImplementation "curse.maven:lets-do-brewery-farm-charm-compat-1038106:7032522"


    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    inputFile.set(shadowJar.archiveFile)
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
